name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ec2-user
      run: |
        set -e  # Exit script if any command fails
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key

        # Copy files to EC2 instance
        scp -i private_key -o StrictHostKeyChecking=no -r ./* ${USER}@${HOST}:~/app
        
        # SSH into EC2 and deploy
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd ~/app
          sudo yum update -y
          sudo amazon-linux-extras install docker -y
          sudo service docker start
          sudo docker build -t flask-app .
          sudo docker stop flask-app || true
          sudo docker rm flask-app || true
          sudo docker run -d --name flask-app -p 80:80 flask-app
        '

        # Clean up the private key
        rm -f private_key
